### ISSUE TITLE
Cleaning up the overview screen

### ISSUE THREAD

**Issue by paaljoachim** [FernleafSystems/Shield-Security-for-WordPress#38]
I cleaned up the overview screen.
As there were too many options and menus. Different sizes. In general it is hard to get an overview because the screen was so busy.

What I removed is likely in other setting pages. I would again suggest that you merge some options into the same screens.

Anyhow here is a new Overview screen. Which I mocked up for you.

The following is the focus of this screen.

![Overview-screen-Shield-Security-Mockup](https://user-images.githubusercontent.com/5323259/97312904-506d4000-1866-11eb-979f-d20d65fe3d00.jpg)

I removed the top menu. Spread the links into various setting screens.
Removed tabs as these are too big and is less important. These should not be on the overview screen.

Cleaned up some of the language. 

For me this is a lot easier to read and understand. My eyes can easier rest while taking in the information.

**Comment by paaljoachim** [comment]
Hey Paul

It would be helpful if you can leave a comment as to changes done for each of the issues you close/closed.
As I am curious what you did with my various suggestions.

**Comment by paulgoodchild** [comment]
A lot has changed in the UI and it factors in some of your suggestions, but are not necessary direct responses to the suggestions. In this case, with the bigger changes, the easiest way to see the differences is to view the plugin itself.

But yes, I can try to do that going forward. 

> It would be helpful if you can leave a comment as to changes done for each of the issues you close.
> As I am curious what you did with my various suggestions.
