### ISSUE TITLE
Improving the Installed plugin area for Shield Security plugin.

### ISSUE THREAD

**Issue by paaljoachim** [FernleafSystems/Shield-Security-for-WordPress#41]
Hey

There is no need to add arrows before and after the Go Pro link. That feels a bit pushy.
Create a great free product and people will want to get the pro version because it offers additional features people experience they want. 

What it looks like today:
<img width="1030" alt="Screen Shot 2020-11-15 at 14 25 16" src="https://user-images.githubusercontent.com/5323259/99186127-6c218300-274e-11eb-8a44-e848fea81da3.png">

Remove the arrows and the 5* Rate This Plugin links.

How it really should look like:
![Shield-security-installed-plugin-screen](https://user-images.githubusercontent.com/5323259/99186169-d1757400-274e-11eb-87aa-d0014a68c830.jpg)

**Comment by paulgoodchild** [comment]
I appreciate that you don't like to see the promotion and encouragement we do for our paid services, and in an ideal world, you'd be right - create a good product and people will want to get pro. It just doesn't work like that in-practice, unfortunately.

This is just text on a screen. It's not getting in the way, and it's not causing problems.
