### ISSUE TITLE
Undefined array key 1 in UpgradeReqLogsTable.php

### ISSUE THREAD

**Issue by consultingroupitaly** [FernleafSystems/Shield-Security-for-WordPress#44]
I get an update to version 14.1.1 and then I get a lot of:
`PHP Warning:  Undefined array key 1 in wp-content/plugins/wp-simple-firewall/src/lib/src/Modules/Data/Lib/UpgradeReqLogsTable.php on line 76`

**Comment by paulgoodchild** [comment]
This wont cause any lasting issues and you can ignore it - once the db table content has all been migrated, the warnings will stop. I'll update the code to ensure it doesn't throw out the warnings in future.

**Comment by consultingroupitaly** [comment]
I know it isn't serious but I have got 52 entries and the site isn't big.
Thanks.

**Comment by paulgoodchild** [comment]
Are you still getting them?

**Comment by consultingroupitaly** [comment]
I don't know how to retrigger the db update again but to avoid the warning is it enough to replace:
`$meta[ 'query' ] = $parts[ 1 ];`
with:
`$meta[ 'query' ] = empty($parts[ 1 ]) ? '' : $parts[ 1 ];`
here:
https://github.com/FernleafSystems/Shield-Security-for-WordPress/blob/master/src/lib/src/Modules/Data/Lib/UpgradeReqLogsTable.php#L79

**Comment by paulgoodchild** [comment]
yep, we have the fix in there for the next release already. The db automatically upgrades itself if it's required so there's nothing you need to do. If you're not getting the error, it means the db table data is fully migrated.
