### ISSUE TITLE
Bug in settings

### ISSUE THREAD

**Issue by consultingroupitaly** [FernleafSystems/Shield-Security-for-WordPress#47]
On this page:
/wp-admin/admin.php?page=icwp-wpsf-insights&inav=settings&subnav=ips#tab-section_logins
selecting "Verify log only", "Disabled" or "Immediately block" works fine but selecting the other 2 seem to work but autorevert to the previous setting.

**Comment by paulgoodchild** [comment]
This isn't something we can reproduce
